before_script:
  - export SOURCE=Core

stages:
- build
- nuget

build:
  tags:
  - docker
  image: microsoft/dotnet:2.2-sdk
  stage: build
  script:
  - dotnet build -c Release
  - dotnet test

nuget:
  tags:
  - docker
  image: microsoft/dotnet:2.2-sdk
  stage: nuget
  only:
  - nuget
  script:
  - dotnet build -c Release
  - dotnet pack ./Core -c Release -o "./artifacts/"
  - dotnet nuget push ./${SOURCE}/artifacts/ --force-english-output -s https://api.nuget.org/v3/index.json -k "${NUGET_API_KEY}"
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*

