stages:
- build
- nuget

build:
  tags:
  - docker
  image: microsoft/dotnet:2.2-sdk
  stage: build
  script:
  - dotnet build -c Release

nuget:
  tags:
  - docker
  image: microsoft/dotnet:2.2-sdk
  stage: nuget
  only:
  - /^v([0-9]+)(\.([0-9]+)){1,2}.*$/
  except:
  - branches
  script:
  - dotnet pack ./Core -c Release -o "${PWD}/artifacts/"
  - dotnet nuget push --force-english-output -s https://api.nuget.org/v3/index.json -k "${NUGET_API_KEY}" ./artifacts/*.nupkg
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*

